---
abstract: 'Evaluate and print out each line before it is executed.'
author:
  - "Marty O'Brien <mob@cpan.org>"
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-DumpTrace
no_index:
  directory:
    - t
    - inc
  package:
    - Text::Shorten
    - Devel::DumpTrace::CachedDisplayedArray
    - Devel::DumpTrace::CachedDisplayedHash
    - Devel::DumpTrace::noPPI
requires:
  Hash::SafeKeys: 0.01
  PadWalker: 1.5
  Scalar::Util: 1.14
  Test::More: 0
version: 0.17
