--- #YAML:1.0
name:               Devel-DumpTrace
version:            0.13
abstract:           Evaluate and print out each line before it is executed.
author:
    - Marty O'Brien <mob@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PadWalker:     1.5
    Scalar::Util:  1.14
    Test::More:    0
no_index:
    directory:
        - t
        - inc
    package:
        - Text::Shorten
        - Devel::DumpTrace::CachedDisplayedArray
        - Devel::DumpTrace::CachedDisplayedHash
        - Devel::DumpTrace::noPPI
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
